name: model-clustering
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v4
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      - uses: actions/setup-python@v4
        with:
           python-version: '3.12'
           
      - name: Install Jinja2
        run: pip install Jinja2

      - name: Install dependencies
        run: |
          pip install tabulate
          
      - uses: iterative/setup-cml@v2
      - name: Clustering model
        run: |
          # Your ML workflow goes here
          pip install -r ReqLibraries.txt
          
          python Code.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          
      # cat metrics.txt >> report.md

          echo "## Visualizing the Clusters" --md >> report.md
          cml-publish Clusters.png --md >> report.md
          cml comment create report.md
